name: AppImage

on:
  push:
    branches: 'master'
    tags: 'v*'
  workflow_dispatch:

jobs:
  Manylinux-Appimage:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64
    env:
      APP_PYTHON_VERSION: "3.11"
    steps:
    - uses: actions/checkout@v3

    - name: Build AppImage
      working-directory: AppImage
      run: bash build-ratarmount-appimage.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ratarmount-x86_64.AppImage
        path: "AppImage/ratarmount*-x86_64.AppImage"


  AppImage-Tests:
    runs-on: ${{ matrix.os }}
    needs: [Manylinux-Appimage]

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ratarmount-x86_64.AppImage

    - name: Install AppImage
      run: |
        chmod u+x ratarmount*-x86_64.AppImage
        mv ratarmount*-x86_64.AppImage /usr/local/bin/ratarmount
        echo "/usr/local/bin" >> $GITHUB_PATH

    - name: Install Dependencies
      run: |
        # These are required for creating test files on the fly not for ratarmount!
        sudo apt-get -y install bzip2 pixz zstd unar fuse

    - name: Test Simple Startup
      run: |
        ratarmount --help
        ratarmount --version

    - uses: actions/checkout@v3

    - name: Test Simple Mount
      run: |
        ratarmount tests/single-file.tar mimi
        ls -la mimi
        sleep 1s
        ratarmount -u mimi

    - name: Regression Tests
      run: |
        export RATARMOUNT_CMD=/usr/local/bin/ratarmount
        bash tests/runtests.sh
